# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Present workign directory
      run: pwd

      - name: Bump Version
        run: |
          # Read the current version from package.json
          current_version=$(node -p -e "require('./package.json').version")
          
          # Calculate the new version (for example, increment the minor version)
          new_version=$(echo $current_version | awk -F. '{$2=$2+1; OFS="."; print $1,$2,$3}')
          
          # Update package.json with the new version
          node -e "const fs = require('fs'); const package = require('./package.json'); package.version = '$new_version'; fs.writeFileSync('./package.json', JSON.stringify(package, null, 2));"

          # Commit the updated version
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -m "Bump version to $new_version" package.json
          git push

        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact-package
        path: ${{ github.workspace }}/target/my-app-1.0-SNAPSHOT.jar